config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  root 'posts#index'
  
  post '/posts/show/:post_id/comments/create' => 'comments#create'
  
  post '/posts/show/:post_id/comments/destroy' => 'comments#destroy'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new
        @comment.title = params[:input_title]
        @comment.content = params[:input_content]
        @comment.post_id = params[:post_id]
        @comment.save
        redirect_to "/posts/#{params[:post_id]}"
    end
    
    def destroy
        @comment = Comment.find()
        @comment.destroy
        redirect_to "/posts/#{params[:post_id]}"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
      if @post.save
         redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else render :edit
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroyredirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>  
  
  <%= stylesheet_link_tag "posts.scss" %>
  
  <title>우리동네 수학대장</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :제목 %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :내용 %><br>
    <%= f.text_area :content, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_nav.html.erb
<ul class="nav justify-content-center">
  
  <li class="nav-item">
    <a class="nav-link active nav-view" href="captain">수학대장</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link nav-view" href="/">묻고 답하기</a>
  </li>

  <% if current_user.nil? %>  
  <li class="nav-item nav-view">
    <%= link_to '로그인', new_user_session_path, class:"nav-link" %>
  </il>
  <% else %>
  <li class="nav-item nav-view">
    <%= link_to '로그아웃', destroy_user_session_path, method: 'delete', class:"nav-link" %>
  </li>
  <% end %>  

  <li class="nav-item">
    <p id="notice", class="nav-link"><%= notice %></p>
  </li>
  
</ul>

app/views/posts/edit.html.erb
<%= render 'nav' %>
<div class="container">
<div class="card">
<div class="card-block">

<%= render 'form' %>

<%= link_to '보기', @post %> |
<%= link_to '뒤로', posts_path %>

</div>
</div>
</div>

app/views/posts/index.html.erb
<%= render 'nav' %>
<hr>
<div class="container">
  
<h1>도와줘요, 수학대장</h1>
<br>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th style="width: 500px;">제목</th>
      <th colspan="1"></th>
      <th><%= link_to '질문하기', new_post_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td scope="row"><%= post.id %></td>
        <td colspan="2"><%= post.title %></td>
        <td>
        <%= link_to '보기', post %>
        <%= link_to '수정', edit_post_path(post) %>
        <%= link_to '삭제', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/posts/new.html.erb
<%= render 'nav' %>
<div class="container", style="margin-top: 50px;">
<div class="card">
<div class="card-block">
<h1>질문하기</h1>

<%= render 'form' %>

<%= link_to '뒤로', posts_path %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<%= render 'nav' %>
<div class="container">
<div class="card">
<div class="card-block">

<form>
  <div class="form-group">
    <label>제목</label>
  <div class="form-control"><%= @post.title %></div>
  </div>
  <div class="form-group">
    <label>내용</label>
  <div class="form-control"><%= @post.content %></div>
  </div>
</form>

<%= link_to '수정', edit_post_path(@post) %> |
<%= link_to '뒤로', posts_path %>

<hr>
<h1>당신의 생각</h1>

<form action='/posts/show/<%= @post.id %>/comments/create' method='post'>
    <div class="field form-group">
    <label>답변</label><br>
  <input type='string' name='input_title' class="form-control">
  </div>
  <br>
  <input type='submit' class="actions">
</form>

<hr>
<% @comments.each do |comment| %>
  <div class="field form-group">
    <label>답변</label><br>
    <div class="form-control"><%= comment.title %></div>
  </div>
<% end %>
<hr>

</div>
</div>
</div>